### ISSUE TITLE
sent message received in multiple channels

### ISSUE THREAD

**Issue by adamteale** [sendbird/sendbird-ios-framework#45]
Hi Guys,

This is most likely caused by something I am doing incorrectly.
I have several Group Channel instances each acting as their own SBDChannelDelegate..

For some reason when a message is sent to one of the channels all of these channel's delegates didReceive methods are called. 

My current work around is to compare the message's channelUrl to the groupChannel channelUrl to make sure that is the intended channel.

Does that make any sense? Any idea what could be causing this? 

SendBirdSDK (3.0.131)

Thanks

Adam

**Comment by BabyAzerty** [comment]
How do you achieve that behaviour? All I see in their SDK is 

```
SBDMain.add(self as SBDChannelDelegate, identifier: "foo")
SBDMain.add(self as SBDConnectionDelegate, identifier: "foo")
```

which relates to SBDMain (so all channels) and not a specific channel.

**Comment by adamteale** [comment]
I have a class that represents an instance of channel, and this implements the channel SBDChannelDelegate methods - in particular the "didReceive message" method :
`
    func channel(_ sender: SBDBaseChannel, didReceive message: SBDBaseMessage) {
        if message.channelUrl == channel?.channelUrl {
             ....
        }
    }
`

**Comment by BabyAzerty** [comment]
Ah yes, it's indeed how the SDK is supposed to work: Because the SendBird delegate is attached to SBDMain and not to a SBDChannel, it is normal that it triggers an event for any message from any channel.

It's a common pattern with Chat SDKs (XMPPFramework, Applozic, etc).

So either you implement it the way you did, directly into your channel object and you compare the urls. 
Or you can have your own ChatManager that is the only one to implement SendBird delegates and dispatch the events to the right channel (sort of adapter class - also helps not having import SendBirdSDK everywhere in your app).
Or you can also have an offline approach where you save directly on disk and you listen to your local DB object changes. And many other ways 😄

**Comment by VladasZ** [comment]
@Kalzem it is kinda strange. What is the purpose of identifier string then?

**Comment by Kalzem** [comment]
@VladasZ It's been a few months since I touched SendBird, but my guess would be that they have a multicast delegates system saved as a dictionary using the identifier as the key. So that when you want to remove a delegate, you give the identifier key.

**Comment by VladasZ** [comment]
@Kalzem in my opinion setting delegate directly to SBDBaseChannel would be more convenient. Protocol called SBDChannelDelegate, not SBDMainDelegate.

**Comment by intoxicated** [comment]
@adamteale like Kalzem said, it is intended behavior. It internally manages delegates in dictionary with associated key identifier. And if when a signature has to be called (for instance, ```channel:didReceiveMessage:``` ), it will go through the delegate dictionary and call if it matches. The main reason why delegate has channel parameter is to give you to decide whether you want to proceed the given message or not for that channel. Thanks

**Comment by intoxicated** [comment]
Please feel free to reopen if you have any questions regards to this behavior.

**Comment by VladasZ** [comment]
Hi! @intoxicated Thanks for the response.
>   it will go through the delegate dictionary and call if it matches.

As the original poster said, and according to my experience there is no check for channel to match the action. On a single message event for a single channel, all channels delegate methods are called in current implementation. It is like if any person in a city receives a mail, the post sends mails to all the citizens, and a citizen must check if the mail is for him and burn it otherwise. If this is intended i don't get the purpose of it. This is not how delegates usually work in iOS SDK. For example if i set UITableViewDelegate i expect to receive the exact UITableView instance i set the delegate for.
