### ISSUE TITLE
v3.0.150 Fails with Bitcode Enabled

### ISSUE THREAD

**Issue by mmoloksher** [sendbird/sendbird-ios-framework#52]
Hello, after upgrading the Sendbird iOS SDK to `v3.0.150` we are no longer able to distribute our application with `Bitcode` enabled. The problem occurs when are trying to export our `.ipa` for Enterprise distribution. 

It seems like in `v3.0.150` support for additional architectures was added which are not compatible with `Bitcode`. 

What is the recommended fix for this? 

![Screen Shot 2019-09-20 at 3 57 06 PM](https://user-images.githubusercontent.com/4513587/65355359-bf865880-dbbf-11e9-8a53-5736ae1259bb.png)

**Comment by mmlittle** [comment]
Hmm.. I'm confused here.. 

What good does bitcode do for an enterprise build?  Distribution is Ad Hoc, so there's no app thinning, therefore bitcode is of no advantage.

Or am I missing something here?

**Comment by sf-jed-kyung** [comment]
Hello,

Thank you for submitting the issue. I've tested exporting an app with the `Include bitcode for iOS content` option or the `Rebuild from Bitcode` option. The deployment target was 8.0 and Xcode version was 11. Since my Apple developer program is not Enterprise, so I couldn't test for `Enterprise distribution`. I just exported my app for `App Store Connect` and `Ad Hoc`, and there were no issues. I'm going to test the same thing on the Enterprise program, but it will take some time.

Thanks.

**Comment by Romulomga** [comment]
Trying export with 3.0.150 version, using fastlane with bitcode enabled and enterprise. Same issue:
![Captura de Tela 2019-09-27 às 19 10 50](https://user-images.githubusercontent.com/23625196/65805060-92efb500-e15a-11e9-8676-a4529ec9cb16.png)

**Comment by sf-jed-kyung** [comment]
Hi all,

We've released v3.0.151. We built the SDK in the new environment, but couldn't test exporting in Enterprise Program. Could you export your apps again with v3.0.151?

**Comment by Romulomga** [comment]
Everything, seems work now!!
![Captura de Tela 2019-09-30 às 16 40 41](https://user-images.githubusercontent.com/23625196/65910460-1d295a80-e3a1-11e9-9941-57d14747e4ca.png)

**Comment by sf-jed-kyung** [comment]
@Romulomga Thank you so much for the testing!
